apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: demo/mutating-webhook-configuration-certificate 
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kubedb-com-v1alpha2-singlestore
  failurePolicy: Fail
  name: msinglestore.kb.io
  rules:
  - apiGroups:
    - kubedb.com
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - singlestores
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: demo/validating-webhook-configuration-certificate
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kubedb-com-v1alpha2-singlestore
  failurePolicy: Fail
  name: vsinglestore.kb.io
  rules:
  - apiGroups:
    - kubedb.com
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - singlestores
  sideEffects: None
