apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: validating-webhook-configuration-certificate
  namespace: demo
spec:
  secretName: validating-webhook-configuration-certificate
  dnsNames:
  - validating-webhook-configuration.demo
  issuerRef:
    name: selfsigned
