apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: mysql-backup
spec:
  image: ashraf10039/mysql-restic-plugin:v0.1.0-rc.1-1-gc67ba7c-dirty_8.0.21_linux_amd64
  args:
  - backup
  - --scratch-dir=${scratchDir:=/tmp}
  - --namespace=${namespace:=default}
  - --backupsession=${backupSession:=}
  - --mysql-args=${args:=}
  - --db-version=8.0.21
---
apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: mysql-restore
spec: 
  image: ashraf10039/mysql-restic-plugin:v0.1.0-rc.1-1-gc67ba7c-dirty_8.0.21_linux_amd64
  args:
  - restore
  - --scratch-dir=${scratchDir:=/tmp}
  - --namespace=${namespace:=default}
  - --restoresession=${restoreSession:=}
  - --snapshot=${snapshot:=}
  - --mysql-args=${args:=}
  - --db-version=8.0.21

