apiVersion: addons.kubestash.com/v1alpha1
kind: Addon
metadata:
  name: mysql-v5-7-25
spec:
  backupTasks:
  - name: mysql-backup
    singleton: true
    function: mysql-backup
    driver: Restic
    parameters:
    - name: args
      usage: Specifies the database args 
      required: false
      default: "--set-gtid-purged=OFF"
  restoreTasks:
  - name: mysql-restore
    singleton: true
    function: mysql-restore
    driver: Restic
    parameters:
    - name: mysql-args
      usage: Specifies the database args 
      required: false
