apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: mysql-backup
spec:
  image: ashraf10039/mysql:refactor_8.0.21_linux_amd64
  args:
  - backup
  - --scratch-dir=${scratchDir:=/tmp}
  - --namespace=${namespace:=default}
  - --backupsession=${backupSession:=}
  - --mysql-args=${args:=}
  - --db-version=5.7.25
---
apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: mysql-restore
spec: 
  image: ashraf10039/mysql:refactor_8.0.21_linux_amd64
  args:
  - restore
  - --scratch-dir=${scratchDir:=/tmp}
  - --namespace=${namespace:=default}
  - --restoresession=${restoreSession:=}
  - --snapshot=${snapshot:=}
  - --mysql-args=${args:=}
  - --db-version=5.7.25

