apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: singlestore-backup
spec:
  image: ashraf10039/singlestore-restic-plugin:start_8.0.21_linux_amd64
  args:
  - backup
  - --scratch-dir=${scratchDir:=/tmp}
  - --namespace=${namespace:=default}
  - --backupsession=${backupSession:=}
  - --singlestore-args=${args:=}
  - --db-version=8.0.21
---
apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: singlestore-restore
spec: 
  image: ashraf10039/singlestore-restic-plugin:start_8.0.21_linux_amd64
  args:
  - restore
  - --scratch-dir=${scratchDir:=/tmp}
  - --namespace=${namespace:=default}
  - --restoresession=${restoreSession:=}
  - --snapshot=${snapshot:=}
  - --singlestore-args=${args:=}
  - --db-version=8.0.21

