apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: singlestore-restoresession
  namespace: demo
spec:
  target:
    name: singlestore-sample
    namespace: demo
    apiGroup: kubedb.com
    kind: Singlestore
  dataSource:
    snapshot: latest
    repository: s3-repo
    encryptionSecret:
      name: encry-secret 
      namespace: demo
  addon:
    name: singlestore-addon
    tasks:
      - name: LogicalBackupRestore
